### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by torch2424** [SamNChiet/PaintBoy#1]
Hello!

This project is super awesome! 😄 Was wondering if there is a license for the game? I like to include open source homebrew on my emulator projects: [WasmBoy](https://github.com/torch2424/wasmboy) and [VaporBoy](https://github.com/torch2424/vaporBoy). And thought this would be a super cool one to add.

Thanks! 👍

**Comment by SamNChiet** [comment]
OOPS
Uh
I'm putting this hereby into the Creative Commons 3 license where people can't sell it but can redistribute and hack on it!

Feel free to include away! I had no idea anyone ever saw this haha, sorry for the late response. And thank you so much!

**Comment by torch2424** [comment]
No worries at all! Thanks for the response I super appreciate it! :smile: :tada:
